// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghbxcqfafscvniegzacd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoYnhjcWZhZnNjdm5pZWd6YWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTQ1ODEsImV4cCI6MjA4ODY3MDU4MX0.zeb9siHEsslQ3IdpopMc1gp5HfXlb5uzpKFxCdn2Y9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});